-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

{-# LANGUAGE FlexibleContexts, FunctionalDependencies, MultiParamTypeClasses,
  UndecidableInstances, OverloadedStrings, TemplateHaskell, TypeApplications,
  TypeFamilies, TupleSections, DataKinds, TypeOperators, FlexibleInstances, RankNTypes,
  AllowAmbiguousTypes, ScopedTypeVariables, DerivingStrategies,
  GeneralizedNewtypeDeriving, LambdaCase, ImplicitPrelude #-}

module Project.Scenes.Test where
import Prelude
import Project.Support
import Godot
import GHC.TypeLits

import Godot.Core.Label()
import Godot.Core.CanvasLayer()

instance SceneResourcePath "Test" where
  sceneResourcePath = "res://Test.tscn"


instance SceneRoot "Test" where
  type SceneRootNode "Test" = "Test"


instance SceneNode        "Test" "Params" where
  type SceneNodeType      "Test" "Params" = Label
  type SceneNodeName      "Test" "Params" = "Params"
  type SceneNodeIsHaskell "Test" "Params" = 'Nothing


instance SceneNode        "Test" "Test" where
  type SceneNodeType      "Test" "Test" = CanvasLayer
  type SceneNodeName      "Test" "Test" = "Test"
  type SceneNodeIsHaskell "Test" "Test" = 'Nothing

