{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TupleSections #-}

module Main where

import Control.Concurrent (threadDelay)
import Control.Lens hiding (from, to)
import Control.Lens.TH
import Control.Monad
import Data.Char
import Data.List
import qualified Data.Map as M
import Data.Maybe
import Data.String.Interpolate
import qualified Data.Text as T
import qualified Data.Text.IO as T
import Debug.Trace
import qualified Language.Haskell.TH.Syntax as TH
import System.Directory
import System.Environment
import System.FSNotify
import System.FilePath
import Prelude hiding (id)

newtype Id = Id {unId :: T.Text}
  deriving (Eq, Ord)
  deriving newtype (Show)

newtype Name = Name {unName :: T.Text}
  deriving (Eq, Ord)
  deriving newtype (Show)

newtype Method = Method {unMethod :: T.Text}
  deriving (Eq, Ord)
  deriving newtype (Show)

newtype Signal = Signal {unSignal :: T.Text}
  deriving (Eq, Ord)
  deriving newtype (Show)

newtype Ty = Ty {unTy :: T.Text}
  deriving (Eq, Ord)
  deriving newtype (Show)

newtype NodePath = NodePath {unNodePath :: T.Text}
  deriving (Eq, Ord)
  deriving newtype (Show)

data Resource = Resource
  { _resourceTy :: Ty,
    _resourcePath :: T.Text
  }
  deriving (Show)

makeFields ''Resource

data TscnNode = TscnNode
  { _tscnNodeTy :: Ty,
    _tscnNodeParent :: Maybe NodePath,
    _tscnNodeInstanceof :: Maybe Id,
    _tscnNodeScript :: Maybe Id
  }
  deriving (Show)

makeFields ''TscnNode

data TscnConnection = TscnConnection
  { _tscnConnectionSignal :: Signal,
    _tscnConnectionFrom :: NodePath,
    _tscnConnectionTo :: NodePath,
    _tscnConnectionMethod :: Method
  }
  deriving (Show)

makeFields ''TscnConnection

data Tscn = Tscn
  { _tscnSceneName :: Name,
    _tscnResources :: M.Map Id Resource,
    _tscnNodes :: M.Map Name TscnNode,
    _tscnConnections :: [TscnConnection],
    _tscnRootNode :: Maybe Name,
    _tscnFilepath :: FilePath
  }
  deriving (Show)

makeFields ''Tscn

data Gdns = Gdns
  { _gdnsExtResources :: M.Map Id Resource,
    _gdnsResources :: M.Map Name Id
  }
  deriving (Show)

makeFields ''Gdns

allByExtension :: String -> FilePath -> IO [String]
allByExtension ext dir = do
  b <- doesDirectoryExist dir
  if b
    then do
      l <- map (dir </>) <$> listDirectory dir
      files <- filterM (\f -> (&& isSuffixOf ext f) <$> doesFileExist f) l
      dirs <- filterM doesDirectoryExist l
      (files ++) . concat <$> mapM (allByExtension ext) dirs
    else pure []

mangle (h : t) = toUpper h : t

createAndWriteFile :: FilePath -> T.Text -> IO ()
createAndWriteFile path content = do
  createDirectoryIfMissing True $ takeDirectory path
  T.writeFile path ("-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT\n\n" <> content)

language =
  [i|{-# LANGUAGE FlexibleContexts, FunctionalDependencies, MultiParamTypeClasses,
  UndecidableInstances, OverloadedStrings, TemplateHaskell, TypeApplications,
  TypeFamilies, TupleSections, DataKinds, TypeOperators, FlexibleInstances, RankNTypes,
  AllowAmbiguousTypes, ScopedTypeVariables, DerivingStrategies,
  GeneralizedNewtypeDeriving, LambdaCase, ImplicitPrelude #-}
|]

mkSceneRoot scene (Just name) =
  T.pack
    [i|
instance SceneRoot "#{mangle $ T.unpack $ unName scene}" where
  type SceneRootNode "#{mangle $ T.unpack $ unName scene}" = "#{unName name}"
|]

mkScenePath scene filepath =
  T.pack
    [i|
instance SceneResourcePath "#{mangle $ T.unpack $ unName scene}" where
  sceneResourcePath = "res://#{filepath}"
|]

mkSceneNode :: FilePath -> String -> T.Text -> Ty -> Ty -> Maybe (Name, Name) -> (T.Text, T.Text)
mkSceneNode scene name path ty ty' isHaskell =
  ( T.pack [i|import Godot.Core.#{ty}()|],
    T.pack
      [i|
instance SceneNode        "#{scene}" "#{path}" where
  type SceneNodeType      "#{scene}" "#{path}" = #{ty'}
  type SceneNodeName      "#{scene}" "#{path}" = "#{name'}"
  type SceneNodeIsHaskell "#{scene}" "#{path}" = #{hsNode}
|]
  )
  where
    name' = T.pack name
    hsNode = case isHaskell of
      Nothing -> "'Nothing"
      Just (Name s, Name n) -> "'Just '(\"" <> s <> "\", \"" <> n <> "\")"

mkSceneConnection scene from signal to method =
  T.pack
    [i|
instance SceneConnection "#{scene}" "#{from}" "#{signal}" "#{to}" "#{method}"
|]

after x = T.drop (T.length x) . snd . T.breakOn x

rowType = Ty . T.takeWhile (/= '\"') . after "type=\""

rowPath = T.takeWhile (/= '\"') . after "path=\"res://"

rowName = Name . T.takeWhile (/= '\"') . after "name=\""

rowParent t =
  NodePath
    <$> if T.isInfixOf " parent=\"" t
      then Just $ T.takeWhile (/= '\"') $ after "parent=\"" t
      else Nothing

rowId = Id . T.takeWhile isNumber . after "id="

rowInstance t =
  Id
    <$> if T.isInfixOf " instance=ExtResource( " t
      then Just $ T.takeWhile isNumber $ after " instance=ExtResource( " t
      else Nothing

resClassName = Name . T.takeWhile (/= '\"') . after "class_name = \""

resScript = Id . T.takeWhile isNumber . after "script = ExtResource( "

resLibrary = Id . T.takeWhile isNumber . after "library = ExtResource( "

rowSignal = Signal . T.takeWhile (/= '\"') . after "signal=\""

rowMethod = Method . T.takeWhile (/= '\"') . after "method=\""

rowFrom current = resolve current . NodePath . T.takeWhile (/= '\"') . after "from=\""

rowTo current = resolve current . NodePath . T.takeWhile (/= '\"') . after "to=\""

resolve :: Maybe Name -> NodePath -> NodePath
resolve (Just (Name n)) (NodePath ".") = NodePath n
resolve _ (NodePath ".") = error "Relative node path without a current node"
resolve _ p = p

readTscn :: FilePath -> FilePath -> IO Tscn
readTscn fn relFile = do
  b <- doesFileExist fn
  let tscnName = Name $ T.pack $ takeBaseName fn
  if b
    then do
      f <- T.lines <$> T.readFile fn
      case f of
        [] -> error $ "Empty .tscn file: " ++ fn
        (h : l) -> do
          if T.isPrefixOf "[gd_scene " h
            then
              pure $
                fillRoot $
                  foldl'
                    ( \(s, current, root) t ->
                        if
                            | T.isPrefixOf "[ext_resource " t ->
                              ( s & resources . at (rowId t) ?~ Resource (rowType t) (rowPath t),
                                current,
                                root
                              )
                            | T.isPrefixOf "[node " t ->
                              ( s & nodes . at (rowName t) ?~ TscnNode (rowType t) (rowParent t) (rowInstance t) Nothing,
                                Just $ rowName t,
                                case rowParent t of
                                  Nothing -> Just $ rowName t
                                  _ -> root
                              )
                            | T.isPrefixOf "[connection " t ->
                              ( s & connections %~ (TscnConnection (rowSignal t) (rowFrom root t) (rowTo root t) (rowMethod t) :),
                                current,
                                root
                              )
                            | T.isPrefixOf "script = ExtResource( " t ->
                              case current of
                                Just name -> (s & nodes . ix name . script ?~ resScript t, current, root)
                            | otherwise -> (s, current, root)
                    )
                    (Tscn tscnName M.empty M.empty [] Nothing relFile, Nothing, Nothing)
                    l
            else pure $ Tscn tscnName M.empty M.empty [] Nothing relFile
    else pure $ Tscn tscnName M.empty M.empty [] Nothing relFile
  where
    fillRoot (tscn, _, root) = tscn & rootNode .~ root

readGdns fn = do
  b <- doesFileExist fn
  if b
    then do
      f <- T.lines <$> T.readFile fn
      case f of
        [] -> error $ "Empty .gdns file: " ++ fn
        (h : l) -> do
          if T.isPrefixOf "[gd_resource type=\"NativeScript\" " h
            then
              pure $
                fst $
                  foldl'
                    ( \(s, current) t ->
                        if
                            | T.isPrefixOf "[ext_resource " t ->
                              (s & extResources . at (rowId t) ?~ Resource (rowType t) (rowPath t), current)
                            | T.isPrefixOf "[" t -> (s, Nothing) -- Reset on any new heading
                            | T.isPrefixOf "class_name =" t -> (s, Just $ resClassName t)
                            | T.isPrefixOf "library = " t ->
                              ( s & resources . at (fromJust current) ?~ resLibrary t,
                                current
                              )
                            | otherwise -> (s, current)
                    )
                    (Gdns M.empty M.empty, Nothing)
                    l
            else pure $ Gdns M.empty M.empty
    else pure $ Gdns M.empty M.empty

main :: IO ()
main = do
  args <- getArgs
  case args of
    [inDir, outDir] -> do
      let regenerate = do
            putStrLn "Regenerating ..."
            gdnsFiles <- allByExtension ".gdns" inDir
            allTscnFiles <- allByExtension ".tscn" inDir
            let scenesWithHaskell = map takeBaseName gdnsFiles

            let tscnFiles = filter ((`elem` scenesWithHaskell) . takeBaseName) allTscnFiles
            mapM_ putStrLn gdnsFiles
            mapM_ putStrLn tscnFiles
            b <- doesDirectoryExist (outDir </> "Project")
            when b $ removeDirectoryRecursive (outDir </> "Project")
            createDirectoryIfMissing True (outDir </> "Project" </> "Scenes")
            ---
            tscns <-
              fmap M.fromList $
                forM tscnFiles $ \f ->
                  let relFile = makeRelative inDir f
                   in (T.pack relFile,) <$> readTscn f relFile
            gdnss <-
              fmap M.fromList $
                forM gdnsFiles $ \f ->
                  (T.pack $ makeRelative inDir f,) <$> readGdns f
            ---
            forM_ (M.toList tscns) $ \(fn, t) ->
              --outputs the Project/Scenes/blah.hs files
              outputTscn (segmentsName inDir fn) (moduleName inDir fn) outDir t tscns gdnss
            --outputs Project/Scenes.hs
            outputCombined inDir outDir tscns
            --outputs Project/Requirements.hs
            outputGdnss inDir outDir gdnss
            putStrLn "Generated!"
            putStrLn "Watching ... ctrl+c to stop"
      regenerate
      withManager $ \mgr -> do
        watchDir
          mgr
          inDir
          ( \e ->
              let ext = takeExtension (eventPath e)
               in ext == ".gdns" || ext == ".tscn"
          )
          ( \a -> do
              regenerate
              print a
          )
        forever $ threadDelay 1000000
    _ -> error "Usage: godot-haskell-project-generator <godot-project-directory> <haskell-src-directory>"

segmentsName :: FilePath -> T.Text -> [[Char]]
segmentsName inDir tscnFilepath =
  map mangle $ filter (/= ".") $ splitPath $ takeDirectory $ T.unpack tscnFilepath

moduleName :: FilePath -> T.Text -> [Char]
moduleName inDir tscnFilepath =
  mangle $ takeBaseName $ T.unpack tscnFilepath

outputTscn :: [FilePath] -> FilePath -> FilePath -> Tscn -> M.Map T.Text Tscn -> M.Map T.Text Gdns -> IO ()
outputTscn segmentsTscnName sceneName outDir tscn tscns gdnss = do
  createAndWriteFile (normalise $ outDir </> "Project" </> "Scenes" </> joinPath segmentsTscnName </> sceneName <> ".hs") $
    T.unlines
      ( [T.pack language, mkModule (toNamespace $ segmentsTscnName <> [sceneName])]
          ++ nub (map fst sceneNodes)
          ++ [ mkScenePath (_tscnSceneName tscn) (tscn ^. filepath),
               mkSceneRoot (_tscnSceneName tscn) (tscn ^. rootNode)
             ]
          ++ map snd sceneNodes
          ++ map
            ( \conn ->
                mkSceneConnection sceneName (conn ^. from) (conn ^. signal) (conn ^. to) (conn ^. method)
            )
            (tscn ^. connections)
      )

  where
    mkModule qualifiedName =
      T.pack
        [i|module Project.Scenes.#{qualifiedName} where
import Prelude
import Godot
|]
    sceneNodes :: [(T.Text, T.Text)]
    sceneNodes =
      flip mapMaybe (M.toList $ tscn ^. nodes) $ \(name, node) -> do
        ty <- case (node ^. ty, node ^. instanceof) of
          (Ty "", Just i) -> case M.lookup i (tscn ^. resources) of
            Just r -> Just $ r ^. ty
            Nothing -> error $ "Can't look up type of " ++ show (name, node)
          -- This happens for nodes from editable scenes
          (Ty "", Nothing) -> Nothing
          (t, _) -> Just t

        return $
          mkSceneNode
            sceneName
            (T.unpack $ unName name)
            ( case node ^. parent of
                Nothing -> unName name
                Just (NodePath ".") -> unName name
                Just (NodePath p') -> p' <> "/" <> unName name
            )
            ty
            (annotatePackedScene node ty)
            (isHaskellNode name node tscn tscns gdnss)

    annotatePackedScene :: TscnNode -> Ty -> Ty
    annotatePackedScene node (Ty "PackedScene") =
      Ty $
        --if there is no root node then it is probably because we have a PackedScene that isn't part of the haskell code
        --so just output it as a Node so we can call functions on it
        case maybeRootNode of
          Nothing -> "Node"
          Just rootNode ->
            "PackedScene' \""
              <> unName rootNode
              <> "\""
      where
      maybeRootNode :: Maybe Name
      maybeRootNode = do
        i <- node ^. instanceof
        r <- M.lookup i (tscn ^. resources)
        tscn <- M.lookup (r ^. path) tscns
        tscn ^. rootNode
    annotatePackedScene node ty = ty

isHaskellNode :: Name -> TscnNode -> Tscn -> M.Map T.Text Tscn -> M.Map T.Text Gdns -> Maybe (Name, Name)
isHaskellNode name node tscn tscns gdnss =
  case ((\f -> tscn ^? resources . at f . _Just . path) =<< (node ^. script), node ^. instanceof) of
    (Just p, _) -> case gdnss ^. at p of
      Just g ->
        if isHaskellGdns name g
          then Just (Name $ T.pack $ dropExtension $ T.unpack p, name)
          else Nothing
      Nothing -> Nothing
    (_, Just i) ->
      let t = tscns ^. at (tscn ^. resources . at i . _Just . path)
       in case (t, rootNodeTscn (fromJust t)) of
            (Just t', Just (n, r)) -> isHaskellNode n r t' tscns gdnss
            _ -> Nothing
    _ -> Nothing

isHaskellGdns :: Name -> Gdns -> Bool
isHaskellGdns n gdns =
  maybe False (\f -> maybe False isHaskellResource (gdns ^. extResources . at f)) (gdns ^. resources . at n)

isHaskellResource :: Resource -> Bool
isHaskellResource r = T.isSuffixOf ".gdnlib" $ r ^. path

rootNodeTscn :: Tscn -> Maybe (Name, TscnNode)
rootNodeTscn tscn = find (\(name, node) -> isNothing (node ^. parent)) $ M.toList $ tscn ^. nodes

outputCombined inDir outDir tscns =
  createAndWriteFile (outDir </> "Project" </> "Scenes.hs") $
    T.pack
      [i|module Project.Scenes where
#{imports}
|]
  where
    imports =
      unlines $
        map
          ( \(fn, t) ->
              let f = toNamespace $ segmentsName inDir fn <> [moduleName inDir fn]
               in [i|import Project.Scenes.#{f}()|]
          )
          $ M.toList tscns

mkRequirementsModule inDir gdnss =
  T.pack
    [i|{-# LANGUAGE DataKinds #-}

module Project.Requirements where
import Godot.Nativescript

type Nodes = '[#{reqs}]
|]
  where
    reqs = intercalate ", " $ map one $ sort $ concatMap (mkRequirement inDir) gdnss
    one (resource, name) = [i|OneResourceNode "#{resource}" "#{name}"|]

outputGdnss :: FilePath -> FilePath -> M.Map T.Text Gdns -> IO ()
outputGdnss inDir dir gdnss = createAndWriteFile (dir </> "Project" </> "Requirements.hs") $ mkRequirementsModule inDir $ M.toList gdnss

mkRequirement :: FilePath -> (T.Text, Gdns) -> [(String, T.Text)]
mkRequirement inDir (fn, gdns) =
  mapMaybe
    ( \(n, i) ->
        case M.lookup i (gdns ^. extResources) of
          Just r ->
            if T.isInfixOf ".gdnlib" (r ^. path) && unTy (r ^. ty) == "GDNativeLibrary"
              then Just (moduleName inDir fn, unName n)
              else Nothing
          _ -> Nothing
    )
    $ M.toList $ gdns ^. resources

toNamespace :: [FilePath] -> String
toNamespace = intercalate "." . fmap dropTrailingPathSeparator
