-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

module Project.Scenes where
import Project.Scenes.HUD()
import Project.Scenes.Main()
import Project.Scenes.Mob()
import Project.Scenes.Player()

